import type { Metadata } from "next";
import Head from "next/head";

import StoreProvider from "@/redux/provider";

import "./globals.css";

export const metadata: Metadata = {
  title: "Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <body>
        <StoreProvider> {children} </StoreProvider>
      </body>
    </html>
  );
}
